all:
	mdpp
	tk run vec1.cpp Readme.md -i 0
	tk run vec2.cpp Readme.md -i 0
	tk run impares1.cpp Readme.md -i 1
	tk run impares2.cpp Readme.md -i 1

mat:
	mdpp Matrizes.md
	tk run mat1.cpp Matrizes.md -i 0
	tk run mat2.cpp Matrizes.md -i 0
	tk run mat3.cpp Matrizes.md -i 1 
	tk run mat4.cpp Matrizes.md -i 2